[package]
name = "vetra-sql"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
vetra-types = { path = "../types" }
vetra-catalog = { path = "../catalog" }

sqlparser = { version = "=0.53.0", default-features = false, features = ["std", "visitor"] }
