[package]
name = "vetra-test-support"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
vetra-types = { path = "../types" }
vetra-io = { path = "../io" }
vetra-engine = { path = "../engine" }
